upgrade scalatest
apache/incubator-pekko-connectors-kafka pull request #58
Opened 2023-04-21 15:49 UTC by pjfanning

2023-04-22 07:19 UTC, raboof commented on .github/workflows/check-build-test.yml
> +        run: sbt ++2.12.17 " ; Test/compile; It/compile"
You can use just `++2.12` so you don't need to keep the minor version in sync manually:

```suggestion
        run: sbt ++2.12 " ; Test/compile; It/compile"
```

2023-04-22 13:50 UTC, pjfanning commented on .github/workflows/check-build-test.yml
> +        run: sbt ++2.12.17 " ; Test/compile; It/compile"
thanks - changed

2023-04-25 11:29 UTC, pjfanning commented
@raboof @mdedetrich @kerr do you think that it is ok to merge this as a step towards Scala 3 support - #59 covers a remaining issue

2023-04-25 12:45 UTC, pjfanning commented
> Need a squash.

done

2023-04-25 13:14 UTC, pjfanning commented on .github/workflows/check-build-test.yml
> +        run: sbt ++2.12 " ; Test/compile; It/compile"
because scala 3 build is not yet 100% working due to the issues with jupiter-junit

2023-04-25 13:15 UTC, mdedetrich commented on .github/workflows/check-build-test.yml
> +        run: sbt ++2.12 " ; Test/compile; It/compile"
Ah I see, can you add this as a comment on the workflow so its more clear?

2023-04-25 13:17 UTC, mdedetrich commented on core/src/main/scala/org/apache/pekko/kafka/scaladsl/DiscoverySupport.scala
> -      case Failure(_: ClassNotFoundException | _: NoClassDefFoundError) =>
What was the context behind this change, more specifically was it done because of a cross compilation Scala 3 issue or some other reason?

2023-04-25 13:19 UTC, mdedetrich commented on tests/src/test/scala/docs/scaladsl/ClusterShardingExample.scala
> +  implicit val system: ActorSystem[_] = ActorSystem(Behaviors.empty, "ClusterShardingExample")
Is this explicit type annotation (as well as others) a cosmetic change or was it necessary for it to compile with Scala 3? Asking because this is located in docs and its a bit out of place especially when compared to other doc code.

2023-04-25 13:21 UTC, pjfanning commented on tests/src/test/scala/docs/scaladsl/ClusterShardingExample.scala
> +  implicit val system: ActorSystem[_] = ActorSystem(Behaviors.empty, "ClusterShardingExample")
scala 3 insists that all implicit variables have explicit type declarations

2023-04-25 13:22 UTC, mdedetrich requested changes
Had a look at the PR, would it be possible to confirm if some of the changes which appear to be cosmetic are cosmetic or necessary for Scala 3. Would be good to only have Scala 3 specific changes in this PR because its easier to track.

2023-04-25 13:22 UTC, mdedetrich commented on tests/src/test/scala/docs/scaladsl/ClusterShardingExample.scala
> +  implicit val system: ActorSystem[_] = ActorSystem(Behaviors.empty, "ClusterShardingExample")
Thanks

2023-04-25 13:23 UTC, mdedetrich commented on core/src/main/scala/org/apache/pekko/kafka/scaladsl/DiscoverySupport.scala
> -      case Failure(_: ClassNotFoundException | _: NoClassDefFoundError) =>
Thanks

2023-04-25 13:24 UTC, mdedetrich commented
Thanks for response, if you can add the comment to `.github/workflows/check-build-test.yml` that would be great then I will approve the PR.

2023-04-25 13:40 UTC, mdedetrich approved these changes
lgtm

2023-04-25 19:43 UTC, merged